### ISSUE TITLE
Power Spectrum option bug

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus_pyqtgraph#30]
Bug found during manual tests on win10 py3qt5 Jul19 release:

How to reproduce
Execute:
<pre>
taurus tpg trend "eval:Q(rand(),'mm')"
</pre>

Right click menu -> Plot Options -> Transforms -> Power Spectrum (FFT) 

<pre>
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\base\taurusbase.py", line 394, in filterEvent
    self.handleEvent(*evt)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus_pyqtgraph\taurustrendset.py", line 269, in handleEvent
    self._addData(xValues, yValues)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus_pyqtgraph\taurustrendset.py", line 251, in _addData
    curve.setData(x=x, y=y[:, i])
  File "c:\miniconda\envs\py3qt5\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 461, in setData
    self.updateItems()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 483, in updateItems
    x,y = self.getData()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 525, in getData
    x,y = self._fourierTransform(x, y)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 683, in _fourierTransform
    y = abs(f[1:len(f)/2])
TypeError: slice indices must be integers or None or have an __index__ method
</pre>

**Comment by cpascual** [comment]
This is almost certainly due to an already fixed but unreleased  bug in pyqtgraph: https://github.com/pyqtgraph/pyqtgraph/pull/429
