### ISSUE TITLE
TypeError when the model is a scalar

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus_pyqtgraph#8]
```
TypeError: object of type 'float' has no len()
Traceback (most recent call last):
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/base/taurusbase.py", line 363, in filterEvent
    self.handleEvent(*evt)
  File "/homelocal/cfalcon/tools/taurus_pyqtgraph/taurus_pyqtgraph/taurusplotdataitem.py", line 86, in handleEvent
    self.setData(x=self._x, y=self._y)
  File "/usr/lib/python2.7/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 447, in setData
    x = np.arange(len(y))
  File "/home/cfalcon/.local/lib/python2.7/site-packages/pint/quantity.py", line 1248, in __len__
    return len(self._magnitude)
TypeError: object of type 'float' has no len()
```

**Comment by cpascual** [comment]
No info is given, but from the traceback I assume this is when setting a scalar to a **tpg.TaurusPlot**, as in e.g.: `taurus --log-level=Debug tpg plot eval:1.2`

In that case, I am rejecting this issue since that is the expected behaviour.
